- name: Please Star First
  # You may pin to the exact commit or the version.
  # uses: uhyo/please-star-first@b020eba8e9a1d89a19268333a1cd606d7abc5a2e
  uses: uhyo/please-star-first@v1.0.0
  with:
    # GitHub token for use by this action.
    token: ${{ secrets.GITHUB_TOKEN }}[0]
    # Message
    message: Let's become friends! Kindly star our repository before opening an issue. Thank You!
