# This is a basic workflow that is manually triggered

name: Starring Partner

on: [issues]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  starcheck:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Please Star First
      uses: uhyo/please-star-first@v1.0.0
      with:
        # GitHub token for use by this action.
        token: ${{ secrets.GITHUB_TOKEN }}
        # Message
        message: Please star this repository before opening an issue.
