# This is a basic workflow that is manually triggered

name: Starring Partner

on:
  issues:
    types: [opened, reopened]
    
jobs:
  # This workflow contains a single job called "greet"
  starcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Please Star First
      uses: qxip/please-star-light@1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        # Message
        message: :star: Please star this repository to motivate the developers and to get priority.
